### ISSUE TITLE
Animating Clipped Shapes

### ISSUE THREAD

**Issue by SvenBudak** [winkerVSbecks/varun.ca-jekyll#10]
https://codepen.io/winkerVSbecks/pen/Nwqoav

Is this also possible only with clip-path?

**Comment by winkerVSbecks** [comment]
Are you referring to the squiggle vision effect or the breaking of shapes?

**Comment by SvenBudak** [comment]
squiggle vision effect :)

**Comment by winkerVSbecks** [comment]
I'm not sure. I only know the SVG filter technique. clip-path might be possible but, I'm not sure it would be worth it. It'll be too complicated.

**Comment by SvenBudak** [comment]
defenetly its worth. because with clip path people can add it to every element they want, also in img tags or divs ;)

**Comment by winkerVSbecks** [comment]
Cool, please do share if you figure it out.

You can re-use the filter technique to apply it to divs etc. by creating a CSS class. More here: https://css-tricks.com/squigglevision-in-css-and-svg/

**Comment by winkerVSbecks** [comment]
Yes, I did publish it a while back. You can grab it here https://www.figma.com/community/plugin/830523897419272248/Jali
