### ISSUE TITLE
Metaballs

### ISSUE THREAD

**Issue by bradyohalloran** [winkerVSbecks/varun.ca-jekyll#4]
In the article at https://varun.ca/metaballs/ where you show the source of the metaball script, there are a couple of wrong variable names.

> function metaballToPath(p1, p2, p3, p4, h1, h2, h3, h4, escaped, r) {
>   return [
>     'M', p1,
>     'C', h1, h3, p3,
>     'A', r, r, 0, escaped ? 1 : 0, 0, p4,
>     'C', h4, h3, p4,
>   ].join(' ');
> }

should be

> function metaballToPath(p1, p2, p3, p4, h1, h2, h3, h4, escaped, r) {
>   return [
>     'M', p1,
>     'C', h1, h3, p3,
>     'A', r, r, 0, escaped ? 1 : 0, 0, p4,
>     'C', h4, **h2**, **p2**,
>   ].join(' ');
> }

It's fine in the Codepen example, but not in the quote in the article

**Comment by winkerVSbecks** [comment]
Thanks

**Comment by shamansir** [comment]
Seems it's still relevant to the last example in the article:

<img width="968" alt="screen shot 2019-02-25 at 21 07 00" src="https://user-images.githubusercontent.com/110920/53365398-6f088e80-3941-11e9-978b-63738db42573.png">

<img width="818" alt="screen shot 2019-02-25 at 21 07 23" src="https://user-images.githubusercontent.com/110920/53365404-7334ac00-3941-11e9-89b2-410aeeb9d1e5.png">
