### ISSUE TITLE
How to handle more complex example

### ISSUE THREAD

**Issue by nicolasletoublon** [winkerVSbecks/varun.ca-jekyll#9]
In the example with the `InputWithAdornment`, you pass down the props to the `HtmlInput`. 
What if the person who needs to use `InputWithAdornment` needs to put some styling at an upper level, for example putting some margin, padding on the whole component ? 
Like :

```
<ParentContainer >
  <InputWithAdornment m={2} p={2} 
     name="currency" 
     before={<Image src="https://icon.now.sh/euro_symbol/333" />}
  />
</ParentContainer>
```

In you implementation I dont see any possibility to pass these m={2} and p={2} to `InputWithAdornment`. Do you have any solution for that ? Because it's all the time the case, where you have your library of components, but they need to be used anywhere!

Thanks!

**Comment by winkerVSbecks** [comment]
It depends on the use case of the specific component and how much flexibility you want to provide to the user. One approach would be to not allow that and recommend that users wrap `InputWithAdornment` in a `Box` to control spacing.

Another approach would be to split props between `Box` and `HtmlInput`.  Where `Box` will receive spacing props and `HtmlInput` the rest.

```js
const InputWithAdornment = ({
  before,
  after,
  disabled,
  p, pt, pr, pb, pl, py, px,
  m, mt, mr, mb, ml, mx, my,
  ...props
}) => {
  const spacingProps = cleanObject({
    p, pt, pr, pb, pl, py, px, m, mt, mr, mb, ml, mx, my,
  });
  
  return (
    <Box display="flex" alignItems="center" position="relative">
      {before && (
        <Adornment left="0" pl={2} disabled={disabled}>
          {before}
        </Adornment>
      )}
      <HtmlInput
        py={2}
        pl={before ? 4 : 2}
        pr={after ? 4 : 2}
        disabled={disabled}
        {...props}
      />
      {after && (
        <Adornment right="0" pr={2} disabled={disabled}>
          {after}
        </Adornment>
      )}
    </Box>
  );
};
```


Or you might want more fine-grained control. For `InputWithAdornment` padding actually impacts a lot within the components. It controls the position of the adornments and where the border is drawn. So, to make padding configurable you would have to account for that logic. 

```js
export const InputWithAdornment = ({
  before,
  after,
  disabled,
  p = 2,
  m, mt, mr, mb, ml, my, mx,
  ...props
}) => {
  const marginProps = cleanObject({ m, mt, mr, mb, ml, my, mx });

  return (
    <Box
      display="flex"
      alignItems="center"
      position="relative"
      {...marginProps}
    >
      {before && (
        <Adornment left="0" pl={p} disabled={disabled}>
          {before}
        </Adornment>
      )}
      <HtmlInput
        py={p}
        pl={before ? 2 * p : p}
        pr={after ? 2 * p : p}
        disabled={disabled}
        {...props}
      />
      {after && (
        <Adornment right="0" pr={p} disabled={disabled}>
          {after}
        </Adornment>
      )}
    </Box>
  );
};
```

full example: https://codesandbox.io/s/43113mx279

**Comment by nicolasletoublon** [comment]
Thanks for the quick answer :) 
I made it possible using a prop called htmlInputProps that you can pass down as MateriaUI does it 
Still the issue is to clean the styled-system ones, because you did it only for margins or padding, but you can change way more than that :D 
So far I think that having a box wrapping it wouldn’t be a bad idea regarding the others solutions! A bit less nice for the consumer, but at least the code would be cleaner for sure ;)

Thanks man!
